#默认使用配置
spring:
  profiles:
    active: dev
server:
  port: 8081
  server.servlet.context-path: /surging
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case : true

---

#开发配置
spring:
  profiles: dev
  thymeleaf:
      prefix: classpath:/templates/
      cache: false
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5

  datasource:
    url: jdbc:mysql://localhost:3306/surgingdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #dataSource Pool configuration
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    exceptionSorter: true
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties:
      druid.stat.mergeSql: true
      druid.stat.slowSqlMillis: 500
    useGlobalDataSourceStat: true

druid:
  login:
    enabled: true
    username: druid
    password: druid