package com.surging.service.impl;

import com.surging.entity.SourceObjectInfo;
import com.surging.entity.SysInfo;
import com.surging.repository.SourceObjectInfoRepository;
import com.surging.repository.SysInfoRepository;
import com.surging.service.IAutoGenerateDDLService;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * Created by zhangdongmao on 2019/3/6.
 */
public class AutoGenerateDDLServiceImpl implements IAutoGenerateDDLService {
    @Autowired
    SourceObjectInfoRepository sourceObjectInfoRepository;
    @Autowired
    SysInfoRepository sysInfoRepository;
    @Override
    public String autoGenerateDDLForHive(String uniqueName) {
        //根据uniquename查询对象名、数据源信息
        SourceObjectInfo sourceObjectInfo=sourceObjectInfoRepository.selectAllByUniqueName(uniqueName);
        String objectName=sourceObjectInfo.getObjectName();
        String sysAbbreviation=sourceObjectInfo.getSysAbbreviation();
        SysInfo sysInfo=sysInfoRepository.selectBySysAbbreviation(sysAbbreviation);




        return null;
    }
}
