package com.surging.entity;

public class ObjectStructure {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_object_structure.database_name
     *
     * @mbggenerated
     */
    private String databaseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_object_structure.sys_abbreviation
     *
     * @mbggenerated
     */
    private String sysAbbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_object_structure.object_name
     *
     * @mbggenerated
     */
    private String objectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_object_structure.unique_name
     *
     * @mbggenerated
     */
    private String uniqueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_object_structure.col_name
     *
     * @mbggenerated
     */
    private String colName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_object_structure.col_type
     *
     * @mbggenerated
     */
    private String colType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_object_structure.partition_key
     *
     * @mbggenerated
     */
    private String partitionKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_object_structure.database_name
     *
     * @return the value of pro_object_structure.database_name
     *
     * @mbggenerated
     */
    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_object_structure.database_name
     *
     * @param databaseName the value for pro_object_structure.database_name
     *
     * @mbggenerated
     */
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName == null ? null : databaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_object_structure.sys_abbreviation
     *
     * @return the value of pro_object_structure.sys_abbreviation
     *
     * @mbggenerated
     */
    public String getSysAbbreviation() {
        return sysAbbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_object_structure.sys_abbreviation
     *
     * @param sysAbbreviation the value for pro_object_structure.sys_abbreviation
     *
     * @mbggenerated
     */
    public void setSysAbbreviation(String sysAbbreviation) {
        this.sysAbbreviation = sysAbbreviation == null ? null : sysAbbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_object_structure.object_name
     *
     * @return the value of pro_object_structure.object_name
     *
     * @mbggenerated
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_object_structure.object_name
     *
     * @param objectName the value for pro_object_structure.object_name
     *
     * @mbggenerated
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName == null ? null : objectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_object_structure.unique_name
     *
     * @return the value of pro_object_structure.unique_name
     *
     * @mbggenerated
     */
    public String getUniqueName() {
        return uniqueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_object_structure.unique_name
     *
     * @param uniqueName the value for pro_object_structure.unique_name
     *
     * @mbggenerated
     */
    public void setUniqueName(String uniqueName) {
        this.uniqueName = uniqueName == null ? null : uniqueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_object_structure.col_name
     *
     * @return the value of pro_object_structure.col_name
     *
     * @mbggenerated
     */
    public String getColName() {
        return colName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_object_structure.col_name
     *
     * @param colName the value for pro_object_structure.col_name
     *
     * @mbggenerated
     */
    public void setColName(String colName) {
        this.colName = colName == null ? null : colName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_object_structure.col_type
     *
     * @return the value of pro_object_structure.col_type
     *
     * @mbggenerated
     */
    public String getColType() {
        return colType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_object_structure.col_type
     *
     * @param colType the value for pro_object_structure.col_type
     *
     * @mbggenerated
     */
    public void setColType(String colType) {
        this.colType = colType == null ? null : colType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_object_structure.partition_key
     *
     * @return the value of pro_object_structure.partition_key
     *
     * @mbggenerated
     */
    public String getPartitionKey() {
        return partitionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_object_structure.partition_key
     *
     * @param partitionKey the value for pro_object_structure.partition_key
     *
     * @mbggenerated
     */
    public void setPartitionKey(String partitionKey) {
        this.partitionKey = partitionKey == null ? null : partitionKey.trim();
    }
}