package com.surging.entity;

public class OdsObjectMetadata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.database_name
     *
     * @mbggenerated
     */
    private String databaseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.unique_name
     *
     * @mbggenerated
     */
    private String uniqueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.object_type
     *
     * @mbggenerated
     */
    private String objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.partitions
     *
     * @mbggenerated
     */
    private String partitions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.field_terminate
     *
     * @mbggenerated
     */
    private String fieldTerminate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.line_terminate
     *
     * @mbggenerated
     */
    private String lineTerminate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.split_by
     *
     * @mbggenerated
     */
    private String splitBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.extract_type
     *
     * @mbggenerated
     */
    private String extractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.increment_column
     *
     * @mbggenerated
     */
    private String incrementColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.extract_days
     *
     * @mbggenerated
     */
    private String extractDays;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.id
     *
     * @return the value of pro_ods_object_metadata.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.id
     *
     * @param id the value for pro_ods_object_metadata.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.database_name
     *
     * @return the value of pro_ods_object_metadata.database_name
     *
     * @mbggenerated
     */
    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.database_name
     *
     * @param databaseName the value for pro_ods_object_metadata.database_name
     *
     * @mbggenerated
     */
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName == null ? null : databaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.unique_name
     *
     * @return the value of pro_ods_object_metadata.unique_name
     *
     * @mbggenerated
     */
    public String getUniqueName() {
        return uniqueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.unique_name
     *
     * @param uniqueName the value for pro_ods_object_metadata.unique_name
     *
     * @mbggenerated
     */
    public void setUniqueName(String uniqueName) {
        this.uniqueName = uniqueName == null ? null : uniqueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.object_type
     *
     * @return the value of pro_ods_object_metadata.object_type
     *
     * @mbggenerated
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.object_type
     *
     * @param objectType the value for pro_ods_object_metadata.object_type
     *
     * @mbggenerated
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.partitions
     *
     * @return the value of pro_ods_object_metadata.partitions
     *
     * @mbggenerated
     */
    public String getPartitions() {
        return partitions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.partitions
     *
     * @param partitions the value for pro_ods_object_metadata.partitions
     *
     * @mbggenerated
     */
    public void setPartitions(String partitions) {
        this.partitions = partitions == null ? null : partitions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.field_terminate
     *
     * @return the value of pro_ods_object_metadata.field_terminate
     *
     * @mbggenerated
     */
    public String getFieldTerminate() {
        return fieldTerminate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.field_terminate
     *
     * @param fieldTerminate the value for pro_ods_object_metadata.field_terminate
     *
     * @mbggenerated
     */
    public void setFieldTerminate(String fieldTerminate) {
        this.fieldTerminate = fieldTerminate == null ? null : fieldTerminate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.line_terminate
     *
     * @return the value of pro_ods_object_metadata.line_terminate
     *
     * @mbggenerated
     */
    public String getLineTerminate() {
        return lineTerminate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.line_terminate
     *
     * @param lineTerminate the value for pro_ods_object_metadata.line_terminate
     *
     * @mbggenerated
     */
    public void setLineTerminate(String lineTerminate) {
        this.lineTerminate = lineTerminate == null ? null : lineTerminate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.comment
     *
     * @return the value of pro_ods_object_metadata.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.comment
     *
     * @param comment the value for pro_ods_object_metadata.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.split_by
     *
     * @return the value of pro_ods_object_metadata.split_by
     *
     * @mbggenerated
     */
    public String getSplitBy() {
        return splitBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.split_by
     *
     * @param splitBy the value for pro_ods_object_metadata.split_by
     *
     * @mbggenerated
     */
    public void setSplitBy(String splitBy) {
        this.splitBy = splitBy == null ? null : splitBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.extract_type
     *
     * @return the value of pro_ods_object_metadata.extract_type
     *
     * @mbggenerated
     */
    public String getExtractType() {
        return extractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.extract_type
     *
     * @param extractType the value for pro_ods_object_metadata.extract_type
     *
     * @mbggenerated
     */
    public void setExtractType(String extractType) {
        this.extractType = extractType == null ? null : extractType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.increment_column
     *
     * @return the value of pro_ods_object_metadata.increment_column
     *
     * @mbggenerated
     */
    public String getIncrementColumn() {
        return incrementColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.increment_column
     *
     * @param incrementColumn the value for pro_ods_object_metadata.increment_column
     *
     * @mbggenerated
     */
    public void setIncrementColumn(String incrementColumn) {
        this.incrementColumn = incrementColumn == null ? null : incrementColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.extract_days
     *
     * @return the value of pro_ods_object_metadata.extract_days
     *
     * @mbggenerated
     */
    public String getExtractDays() {
        return extractDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.extract_days
     *
     * @param extractDays the value for pro_ods_object_metadata.extract_days
     *
     * @mbggenerated
     */
    public void setExtractDays(String extractDays) {
        this.extractDays = extractDays == null ? null : extractDays.trim();
    }
}