package com.surging.entity;

public class OdsObjectMetadataWithBLOBs extends OdsObjectMetadata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.query
     *
     * @mbggenerated
     */
    private String query;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.hive_ddl
     *
     * @mbggenerated
     */
    private String hiveDdl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_ods_object_metadata.increment_script
     *
     * @mbggenerated
     */
    private String incrementScript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.query
     *
     * @return the value of pro_ods_object_metadata.query
     *
     * @mbggenerated
     */
    public String getQuery() {
        return query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.query
     *
     * @param query the value for pro_ods_object_metadata.query
     *
     * @mbggenerated
     */
    public void setQuery(String query) {
        this.query = query == null ? null : query.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.hive_ddl
     *
     * @return the value of pro_ods_object_metadata.hive_ddl
     *
     * @mbggenerated
     */
    public String getHiveDdl() {
        return hiveDdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.hive_ddl
     *
     * @param hiveDdl the value for pro_ods_object_metadata.hive_ddl
     *
     * @mbggenerated
     */
    public void setHiveDdl(String hiveDdl) {
        this.hiveDdl = hiveDdl == null ? null : hiveDdl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_ods_object_metadata.increment_script
     *
     * @return the value of pro_ods_object_metadata.increment_script
     *
     * @mbggenerated
     */
    public String getIncrementScript() {
        return incrementScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_ods_object_metadata.increment_script
     *
     * @param incrementScript the value for pro_ods_object_metadata.increment_script
     *
     * @mbggenerated
     */
    public void setIncrementScript(String incrementScript) {
        this.incrementScript = incrementScript == null ? null : incrementScript.trim();
    }
}