package com.surging.entity;

public class ScriptStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column script_store.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column script_store.unique_name
     *
     * @mbggenerated
     */
    private String uniqueName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column script_store.id
     *
     * @return the value of script_store.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column script_store.id
     *
     * @param id the value for script_store.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column script_store.unique_name
     *
     * @return the value of script_store.unique_name
     *
     * @mbggenerated
     */
    public String getUniqueName() {
        return uniqueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column script_store.unique_name
     *
     * @param uniqueName the value for script_store.unique_name
     *
     * @mbggenerated
     */
    public void setUniqueName(String uniqueName) {
        this.uniqueName = uniqueName == null ? null : uniqueName.trim();
    }
}