package com.surging.entity;

public class ScriptStoreWithBLOBs extends ScriptStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column script_store.hive_ddl
     *
     * @mbggenerated
     */
    private String hiveDdl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column script_store.increment_script
     *
     * @mbggenerated
     */
    private String incrementScript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column script_store.hive_ddl
     *
     * @return the value of script_store.hive_ddl
     *
     * @mbggenerated
     */
    public String getHiveDdl() {
        return hiveDdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column script_store.hive_ddl
     *
     * @param hiveDdl the value for script_store.hive_ddl
     *
     * @mbggenerated
     */
    public void setHiveDdl(String hiveDdl) {
        this.hiveDdl = hiveDdl == null ? null : hiveDdl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column script_store.increment_script
     *
     * @return the value of script_store.increment_script
     *
     * @mbggenerated
     */
    public String getIncrementScript() {
        return incrementScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column script_store.increment_script
     *
     * @param incrementScript the value for script_store.increment_script
     *
     * @mbggenerated
     */
    public void setIncrementScript(String incrementScript) {
        this.incrementScript = incrementScript == null ? null : incrementScript.trim();
    }
}