package com.surging.entity;

public class SourceObjectInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.object_name
     *
     * @mbggenerated
     */
    private String objectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.database_type
     *
     * @mbggenerated
     */
    private String databaseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.sys_abbreviation
     *
     * @mbggenerated
     */
    private String sysAbbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.unique_name
     *
     * @mbggenerated
     */
    private String uniqueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.owner
     *
     * @mbggenerated
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.object_type
     *
     * @mbggenerated
     */
    private String objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.primary_key
     *
     * @mbggenerated
     */
    private String primaryKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.unique_index
     *
     * @mbggenerated
     */
    private String uniqueIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.data_volume
     *
     * @mbggenerated
     */
    private String dataVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.db_env
     *
     * @mbggenerated
     */
    private String dbEnv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.create_dt
     *
     * @mbggenerated
     */
    private String createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.pic
     *
     * @mbggenerated
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_info.develop_status
     *
     * @mbggenerated
     */
    private String developStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.id
     *
     * @return the value of source_object_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.id
     *
     * @param id the value for source_object_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.level
     *
     * @return the value of source_object_info.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.level
     *
     * @param level the value for source_object_info.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.object_name
     *
     * @return the value of source_object_info.object_name
     *
     * @mbggenerated
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.object_name
     *
     * @param objectName the value for source_object_info.object_name
     *
     * @mbggenerated
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName == null ? null : objectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.database_type
     *
     * @return the value of source_object_info.database_type
     *
     * @mbggenerated
     */
    public String getDatabaseType() {
        return databaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.database_type
     *
     * @param databaseType the value for source_object_info.database_type
     *
     * @mbggenerated
     */
    public void setDatabaseType(String databaseType) {
        this.databaseType = databaseType == null ? null : databaseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.sys_abbreviation
     *
     * @return the value of source_object_info.sys_abbreviation
     *
     * @mbggenerated
     */
    public String getSysAbbreviation() {
        return sysAbbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.sys_abbreviation
     *
     * @param sysAbbreviation the value for source_object_info.sys_abbreviation
     *
     * @mbggenerated
     */
    public void setSysAbbreviation(String sysAbbreviation) {
        this.sysAbbreviation = sysAbbreviation == null ? null : sysAbbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.unique_name
     *
     * @return the value of source_object_info.unique_name
     *
     * @mbggenerated
     */
    public String getUniqueName() {
        return uniqueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.unique_name
     *
     * @param uniqueName the value for source_object_info.unique_name
     *
     * @mbggenerated
     */
    public void setUniqueName(String uniqueName) {
        this.uniqueName = uniqueName == null ? null : uniqueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.owner
     *
     * @return the value of source_object_info.owner
     *
     * @mbggenerated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.owner
     *
     * @param owner the value for source_object_info.owner
     *
     * @mbggenerated
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.object_type
     *
     * @return the value of source_object_info.object_type
     *
     * @mbggenerated
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.object_type
     *
     * @param objectType the value for source_object_info.object_type
     *
     * @mbggenerated
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.primary_key
     *
     * @return the value of source_object_info.primary_key
     *
     * @mbggenerated
     */
    public String getPrimaryKey() {
        return primaryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.primary_key
     *
     * @param primaryKey the value for source_object_info.primary_key
     *
     * @mbggenerated
     */
    public void setPrimaryKey(String primaryKey) {
        this.primaryKey = primaryKey == null ? null : primaryKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.unique_index
     *
     * @return the value of source_object_info.unique_index
     *
     * @mbggenerated
     */
    public String getUniqueIndex() {
        return uniqueIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.unique_index
     *
     * @param uniqueIndex the value for source_object_info.unique_index
     *
     * @mbggenerated
     */
    public void setUniqueIndex(String uniqueIndex) {
        this.uniqueIndex = uniqueIndex == null ? null : uniqueIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.data_volume
     *
     * @return the value of source_object_info.data_volume
     *
     * @mbggenerated
     */
    public String getDataVolume() {
        return dataVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.data_volume
     *
     * @param dataVolume the value for source_object_info.data_volume
     *
     * @mbggenerated
     */
    public void setDataVolume(String dataVolume) {
        this.dataVolume = dataVolume == null ? null : dataVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.db_env
     *
     * @return the value of source_object_info.db_env
     *
     * @mbggenerated
     */
    public String getDbEnv() {
        return dbEnv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.db_env
     *
     * @param dbEnv the value for source_object_info.db_env
     *
     * @mbggenerated
     */
    public void setDbEnv(String dbEnv) {
        this.dbEnv = dbEnv == null ? null : dbEnv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.create_dt
     *
     * @return the value of source_object_info.create_dt
     *
     * @mbggenerated
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.create_dt
     *
     * @param createDt the value for source_object_info.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.create_by
     *
     * @return the value of source_object_info.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.create_by
     *
     * @param createBy the value for source_object_info.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.pic
     *
     * @return the value of source_object_info.pic
     *
     * @mbggenerated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.pic
     *
     * @param pic the value for source_object_info.pic
     *
     * @mbggenerated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_info.develop_status
     *
     * @return the value of source_object_info.develop_status
     *
     * @mbggenerated
     */
    public String getDevelopStatus() {
        return developStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_info.develop_status
     *
     * @param developStatus the value for source_object_info.develop_status
     *
     * @mbggenerated
     */
    public void setDevelopStatus(String developStatus) {
        this.developStatus = developStatus == null ? null : developStatus.trim();
    }
}