package com.surging.entity;

public class SourceStructure {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_structure.unique_name
     *
     * @mbggenerated
     */
    private String uniqueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_structure.column_name
     *
     * @mbggenerated
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_structure.column_type
     *
     * @mbggenerated
     */
    private String columnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_structure.data_length
     *
     * @mbggenerated
     */
    private String dataLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_structure.data_precision
     *
     * @mbggenerated
     */
    private String dataPrecision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_structure.data_scale
     *
     * @mbggenerated
     */
    private String dataScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_structure.is_nullable
     *
     * @mbggenerated
     */
    private String isNullable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_structure.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_structure.unique_name
     *
     * @return the value of source_structure.unique_name
     *
     * @mbggenerated
     */
    public String getUniqueName() {
        return uniqueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_structure.unique_name
     *
     * @param uniqueName the value for source_structure.unique_name
     *
     * @mbggenerated
     */
    public void setUniqueName(String uniqueName) {
        this.uniqueName = uniqueName == null ? null : uniqueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_structure.column_name
     *
     * @return the value of source_structure.column_name
     *
     * @mbggenerated
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_structure.column_name
     *
     * @param columnName the value for source_structure.column_name
     *
     * @mbggenerated
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_structure.column_type
     *
     * @return the value of source_structure.column_type
     *
     * @mbggenerated
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_structure.column_type
     *
     * @param columnType the value for source_structure.column_type
     *
     * @mbggenerated
     */
    public void setColumnType(String columnType) {
        this.columnType = columnType == null ? null : columnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_structure.data_length
     *
     * @return the value of source_structure.data_length
     *
     * @mbggenerated
     */
    public String getDataLength() {
        return dataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_structure.data_length
     *
     * @param dataLength the value for source_structure.data_length
     *
     * @mbggenerated
     */
    public void setDataLength(String dataLength) {
        this.dataLength = dataLength == null ? null : dataLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_structure.data_precision
     *
     * @return the value of source_structure.data_precision
     *
     * @mbggenerated
     */
    public String getDataPrecision() {
        return dataPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_structure.data_precision
     *
     * @param dataPrecision the value for source_structure.data_precision
     *
     * @mbggenerated
     */
    public void setDataPrecision(String dataPrecision) {
        this.dataPrecision = dataPrecision == null ? null : dataPrecision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_structure.data_scale
     *
     * @return the value of source_structure.data_scale
     *
     * @mbggenerated
     */
    public String getDataScale() {
        return dataScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_structure.data_scale
     *
     * @param dataScale the value for source_structure.data_scale
     *
     * @mbggenerated
     */
    public void setDataScale(String dataScale) {
        this.dataScale = dataScale == null ? null : dataScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_structure.is_nullable
     *
     * @return the value of source_structure.is_nullable
     *
     * @mbggenerated
     */
    public String getIsNullable() {
        return isNullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_structure.is_nullable
     *
     * @param isNullable the value for source_structure.is_nullable
     *
     * @mbggenerated
     */
    public void setIsNullable(String isNullable) {
        this.isNullable = isNullable == null ? null : isNullable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_structure.comment
     *
     * @return the value of source_structure.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_structure.comment
     *
     * @param comment the value for source_structure.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}