package com.surging.entity;

public class SourceObjectList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_list.source_object_id
     *
     * @mbggenerated
     */
    private Integer sourceObjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_list.database_type
     *
     * @mbggenerated
     */
    private String databaseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_list.sys_abbreviation
     *
     * @mbggenerated
     */
    private String sysAbbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_list.object_name
     *
     * @mbggenerated
     */
    private String objectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_list.unique_name
     *
     * @mbggenerated
     */
    private String uniqueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_list.owner
     *
     * @mbggenerated
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_list.object_type
     *
     * @mbggenerated
     */
    private String objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_object_list.create_dt
     *
     * @mbggenerated
     */
    private String createDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_list.source_object_id
     *
     * @return the value of source_object_list.source_object_id
     *
     * @mbggenerated
     */
    public Integer getSourceObjectId() {
        return sourceObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_list.source_object_id
     *
     * @param sourceObjectId the value for source_object_list.source_object_id
     *
     * @mbggenerated
     */
    public void setSourceObjectId(Integer sourceObjectId) {
        this.sourceObjectId = sourceObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_list.database_type
     *
     * @return the value of source_object_list.database_type
     *
     * @mbggenerated
     */
    public String getDatabaseType() {
        return databaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_list.database_type
     *
     * @param databaseType the value for source_object_list.database_type
     *
     * @mbggenerated
     */
    public void setDatabaseType(String databaseType) {
        this.databaseType = databaseType == null ? null : databaseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_list.sys_abbreviation
     *
     * @return the value of source_object_list.sys_abbreviation
     *
     * @mbggenerated
     */
    public String getSysAbbreviation() {
        return sysAbbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_list.sys_abbreviation
     *
     * @param sysAbbreviation the value for source_object_list.sys_abbreviation
     *
     * @mbggenerated
     */
    public void setSysAbbreviation(String sysAbbreviation) {
        this.sysAbbreviation = sysAbbreviation == null ? null : sysAbbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_list.object_name
     *
     * @return the value of source_object_list.object_name
     *
     * @mbggenerated
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_list.object_name
     *
     * @param objectName the value for source_object_list.object_name
     *
     * @mbggenerated
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName == null ? null : objectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_list.unique_name
     *
     * @return the value of source_object_list.unique_name
     *
     * @mbggenerated
     */
    public String getUniqueName() {
        return uniqueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_list.unique_name
     *
     * @param uniqueName the value for source_object_list.unique_name
     *
     * @mbggenerated
     */
    public void setUniqueName(String uniqueName) {
        this.uniqueName = uniqueName == null ? null : uniqueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_list.owner
     *
     * @return the value of source_object_list.owner
     *
     * @mbggenerated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_list.owner
     *
     * @param owner the value for source_object_list.owner
     *
     * @mbggenerated
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_list.object_type
     *
     * @return the value of source_object_list.object_type
     *
     * @mbggenerated
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_list.object_type
     *
     * @param objectType the value for source_object_list.object_type
     *
     * @mbggenerated
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_object_list.create_dt
     *
     * @return the value of source_object_list.create_dt
     *
     * @mbggenerated
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_object_list.create_dt
     *
     * @param createDt the value for source_object_list.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }
}