package com.surging.entity;

public class SysInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.sys_abbreviation
     *
     * @mbggenerated
     */
    private String sysAbbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.sys_name
     *
     * @mbggenerated
     */
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.database_version
     *
     * @mbggenerated
     */
    private String databaseVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.database_type
     *
     * @mbggenerated
     */
    private String databaseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.port
     *
     * @mbggenerated
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.jdbc_url
     *
     * @mbggenerated
     */
    private String jdbcUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.db_username
     *
     * @mbggenerated
     */
    private String dbUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.db_password
     *
     * @mbggenerated
     */
    private String dbPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.etl_time
     *
     * @mbggenerated
     */
    private String etlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.sys_type
     *
     * @mbggenerated
     */
    private String sysType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.id
     *
     * @return the value of sys_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.id
     *
     * @param id the value for sys_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.sys_abbreviation
     *
     * @return the value of sys_info.sys_abbreviation
     *
     * @mbggenerated
     */
    public String getSysAbbreviation() {
        return sysAbbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.sys_abbreviation
     *
     * @param sysAbbreviation the value for sys_info.sys_abbreviation
     *
     * @mbggenerated
     */
    public void setSysAbbreviation(String sysAbbreviation) {
        this.sysAbbreviation = sysAbbreviation == null ? null : sysAbbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.sys_name
     *
     * @return the value of sys_info.sys_name
     *
     * @mbggenerated
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.sys_name
     *
     * @param sysName the value for sys_info.sys_name
     *
     * @mbggenerated
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.sid
     *
     * @return the value of sys_info.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.sid
     *
     * @param sid the value for sys_info.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.database_version
     *
     * @return the value of sys_info.database_version
     *
     * @mbggenerated
     */
    public String getDatabaseVersion() {
        return databaseVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.database_version
     *
     * @param databaseVersion the value for sys_info.database_version
     *
     * @mbggenerated
     */
    public void setDatabaseVersion(String databaseVersion) {
        this.databaseVersion = databaseVersion == null ? null : databaseVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.database_type
     *
     * @return the value of sys_info.database_type
     *
     * @mbggenerated
     */
    public String getDatabaseType() {
        return databaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.database_type
     *
     * @param databaseType the value for sys_info.database_type
     *
     * @mbggenerated
     */
    public void setDatabaseType(String databaseType) {
        this.databaseType = databaseType == null ? null : databaseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.ip
     *
     * @return the value of sys_info.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.ip
     *
     * @param ip the value for sys_info.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.port
     *
     * @return the value of sys_info.port
     *
     * @mbggenerated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.port
     *
     * @param port the value for sys_info.port
     *
     * @mbggenerated
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.jdbc_url
     *
     * @return the value of sys_info.jdbc_url
     *
     * @mbggenerated
     */
    public String getJdbcUrl() {
        return jdbcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.jdbc_url
     *
     * @param jdbcUrl the value for sys_info.jdbc_url
     *
     * @mbggenerated
     */
    public void setJdbcUrl(String jdbcUrl) {
        this.jdbcUrl = jdbcUrl == null ? null : jdbcUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.db_username
     *
     * @return the value of sys_info.db_username
     *
     * @mbggenerated
     */
    public String getDbUsername() {
        return dbUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.db_username
     *
     * @param dbUsername the value for sys_info.db_username
     *
     * @mbggenerated
     */
    public void setDbUsername(String dbUsername) {
        this.dbUsername = dbUsername == null ? null : dbUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.db_password
     *
     * @return the value of sys_info.db_password
     *
     * @mbggenerated
     */
    public String getDbPassword() {
        return dbPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.db_password
     *
     * @param dbPassword the value for sys_info.db_password
     *
     * @mbggenerated
     */
    public void setDbPassword(String dbPassword) {
        this.dbPassword = dbPassword == null ? null : dbPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.etl_time
     *
     * @return the value of sys_info.etl_time
     *
     * @mbggenerated
     */
    public String getEtlTime() {
        return etlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.etl_time
     *
     * @param etlTime the value for sys_info.etl_time
     *
     * @mbggenerated
     */
    public void setEtlTime(String etlTime) {
        this.etlTime = etlTime == null ? null : etlTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.sys_type
     *
     * @return the value of sys_info.sys_type
     *
     * @mbggenerated
     */
    public String getSysType() {
        return sysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.sys_type
     *
     * @param sysType the value for sys_info.sys_type
     *
     * @mbggenerated
     */
    public void setSysType(String sysType) {
        this.sysType = sysType == null ? null : sysType.trim();
    }
}