package com.surging.entity;

import java.util.Date;

public class WorkList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.object_name
     *
     * @mbggenerated
     */
    private String objectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.sys_info_id
     *
     * @mbggenerated
     */
    private Integer sysInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.developer_id
     *
     * @mbggenerated
     */
    private Integer developerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.develop_status
     *
     * @mbggenerated
     */
    private String developStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.plan_develop_time
     *
     * @mbggenerated
     */
    private String planDevelopTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.object_type
     *
     * @mbggenerated
     */
    private String objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.schema
     *
     * @mbggenerated
     */
    private String schema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.big_table
     *
     * @mbggenerated
     */
    private String bigTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.increment_column
     *
     * @mbggenerated
     */
    private String incrementColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.split_column
     *
     * @mbggenerated
     */
    private String splitColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.extract_type
     *
     * @mbggenerated
     */
    private String extractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.init_script
     *
     * @mbggenerated
     */
    private String initScript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.init_big_script
     *
     * @mbggenerated
     */
    private String initBigScript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.full_script
     *
     * @mbggenerated
     */
    private String fullScript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.increment_script
     *
     * @mbggenerated
     */
    private String incrementScript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.table_ddl
     *
     * @mbggenerated
     */
    private String tableDdl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_list.last_update_date
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.id
     *
     * @return the value of work_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.id
     *
     * @param id the value for work_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.object_name
     *
     * @return the value of work_list.object_name
     *
     * @mbggenerated
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.object_name
     *
     * @param objectName the value for work_list.object_name
     *
     * @mbggenerated
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName == null ? null : objectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.sys_info_id
     *
     * @return the value of work_list.sys_info_id
     *
     * @mbggenerated
     */
    public Integer getSysInfoId() {
        return sysInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.sys_info_id
     *
     * @param sysInfoId the value for work_list.sys_info_id
     *
     * @mbggenerated
     */
    public void setSysInfoId(Integer sysInfoId) {
        this.sysInfoId = sysInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.developer_id
     *
     * @return the value of work_list.developer_id
     *
     * @mbggenerated
     */
    public Integer getDeveloperId() {
        return developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.developer_id
     *
     * @param developerId the value for work_list.developer_id
     *
     * @mbggenerated
     */
    public void setDeveloperId(Integer developerId) {
        this.developerId = developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.develop_status
     *
     * @return the value of work_list.develop_status
     *
     * @mbggenerated
     */
    public String getDevelopStatus() {
        return developStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.develop_status
     *
     * @param developStatus the value for work_list.develop_status
     *
     * @mbggenerated
     */
    public void setDevelopStatus(String developStatus) {
        this.developStatus = developStatus == null ? null : developStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.plan_develop_time
     *
     * @return the value of work_list.plan_develop_time
     *
     * @mbggenerated
     */
    public String getPlanDevelopTime() {
        return planDevelopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.plan_develop_time
     *
     * @param planDevelopTime the value for work_list.plan_develop_time
     *
     * @mbggenerated
     */
    public void setPlanDevelopTime(String planDevelopTime) {
        this.planDevelopTime = planDevelopTime == null ? null : planDevelopTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.object_type
     *
     * @return the value of work_list.object_type
     *
     * @mbggenerated
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.object_type
     *
     * @param objectType the value for work_list.object_type
     *
     * @mbggenerated
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.schema
     *
     * @return the value of work_list.schema
     *
     * @mbggenerated
     */
    public String getSchema() {
        return schema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.schema
     *
     * @param schema the value for work_list.schema
     *
     * @mbggenerated
     */
    public void setSchema(String schema) {
        this.schema = schema == null ? null : schema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.big_table
     *
     * @return the value of work_list.big_table
     *
     * @mbggenerated
     */
    public String getBigTable() {
        return bigTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.big_table
     *
     * @param bigTable the value for work_list.big_table
     *
     * @mbggenerated
     */
    public void setBigTable(String bigTable) {
        this.bigTable = bigTable == null ? null : bigTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.increment_column
     *
     * @return the value of work_list.increment_column
     *
     * @mbggenerated
     */
    public String getIncrementColumn() {
        return incrementColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.increment_column
     *
     * @param incrementColumn the value for work_list.increment_column
     *
     * @mbggenerated
     */
    public void setIncrementColumn(String incrementColumn) {
        this.incrementColumn = incrementColumn == null ? null : incrementColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.split_column
     *
     * @return the value of work_list.split_column
     *
     * @mbggenerated
     */
    public String getSplitColumn() {
        return splitColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.split_column
     *
     * @param splitColumn the value for work_list.split_column
     *
     * @mbggenerated
     */
    public void setSplitColumn(String splitColumn) {
        this.splitColumn = splitColumn == null ? null : splitColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.extract_type
     *
     * @return the value of work_list.extract_type
     *
     * @mbggenerated
     */
    public String getExtractType() {
        return extractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.extract_type
     *
     * @param extractType the value for work_list.extract_type
     *
     * @mbggenerated
     */
    public void setExtractType(String extractType) {
        this.extractType = extractType == null ? null : extractType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.init_script
     *
     * @return the value of work_list.init_script
     *
     * @mbggenerated
     */
    public String getInitScript() {
        return initScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.init_script
     *
     * @param initScript the value for work_list.init_script
     *
     * @mbggenerated
     */
    public void setInitScript(String initScript) {
        this.initScript = initScript == null ? null : initScript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.init_big_script
     *
     * @return the value of work_list.init_big_script
     *
     * @mbggenerated
     */
    public String getInitBigScript() {
        return initBigScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.init_big_script
     *
     * @param initBigScript the value for work_list.init_big_script
     *
     * @mbggenerated
     */
    public void setInitBigScript(String initBigScript) {
        this.initBigScript = initBigScript == null ? null : initBigScript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.full_script
     *
     * @return the value of work_list.full_script
     *
     * @mbggenerated
     */
    public String getFullScript() {
        return fullScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.full_script
     *
     * @param fullScript the value for work_list.full_script
     *
     * @mbggenerated
     */
    public void setFullScript(String fullScript) {
        this.fullScript = fullScript == null ? null : fullScript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.increment_script
     *
     * @return the value of work_list.increment_script
     *
     * @mbggenerated
     */
    public String getIncrementScript() {
        return incrementScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.increment_script
     *
     * @param incrementScript the value for work_list.increment_script
     *
     * @mbggenerated
     */
    public void setIncrementScript(String incrementScript) {
        this.incrementScript = incrementScript == null ? null : incrementScript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.table_ddl
     *
     * @return the value of work_list.table_ddl
     *
     * @mbggenerated
     */
    public String getTableDdl() {
        return tableDdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.table_ddl
     *
     * @param tableDdl the value for work_list.table_ddl
     *
     * @mbggenerated
     */
    public void setTableDdl(String tableDdl) {
        this.tableDdl = tableDdl == null ? null : tableDdl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_list.last_update_date
     *
     * @return the value of work_list.last_update_date
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_list.last_update_date
     *
     * @param lastUpdateDate the value for work_list.last_update_date
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}